### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by xavi7th** [mdownes/rollup-plugin-concat#1]
When the output folder does not exist, it throws an error. Is there a way to configure the plugin to create the folder tree if not existent?

Thank you

**Comment by xavi7th** [comment]
I figured this out.

You need to make sure the directory structure pre-exists

I solved this by

```import fs from "node:fs";```

```javascript
const folderName = 'public/build/assets';

  try {
    if (!fs.existsSync(folderName)) {
      fs.mkdirSync(folderName, {recursive: true});
    }
  } catch (err) {
    console.error(err);
  }
```

This will create the folder structure if it doesn't exist

**Comment by mdownes** [comment]
Have updated package to create folder if it doesn't already exist.
